pull_request_rules:
  # approve
  - name: automatic approval
    conditions:
      - author=dsm23
      - check-success=amd64
      - check-success=build
      - check-success~=codeql \([a-z]*\)
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success=lint
      - check-success~=playwright-tests \(\d, \d\)
      - "#check-success>=17"
    actions:
      review:
        type: APPROVE
        message: Automatically approving dsm23
  - name: automatic approval for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=amd64
      - check-success=build
      - check-success~=codeql \([a-z]*\)
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success=lint
      - check-success~=playwright-tests \(\d, \d\)
      - "#check-success>=17"
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
  # merge
  - name: Automatically merge when GitHub Actions jobs succeed
    conditions:
      - check-success=amd64
      - check-success=build
      - check-success~=codeql \([a-z]*\)
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success=lint
      - check-success~=playwright-tests \(\d, \d\)
      - "#check-success>=17"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
